### ISSUE TITLE
If possible, please include precompiled obj-files for Win64 for Delphi

### ISSUE THREAD

**Issue by TommiPrami** [zedxxx/libdeflate-pas#1]
Would be much appreciated, thanks.

-Tee-

**Comment by zedxxx** [comment]
I don't have Embarcadero C++ compiler for this.

**Comment by TommiPrami** [comment]
Dang,

Maybe someone else can chip in ..

Let's wait 😉

-tee-

**Comment by zedxxx** [comment]
fixed: https://github.com/zedxxx/libdeflate-pas/commit/7702f5587de2ed541aad6efdea1ff5ddf0c74460
